### ISSUE TITLE
Hogex/pegins address is incorrectly encoded with bech32m instead of bech32.

### ISSUE THREAD

**Issue by losh11** [rust-litecoin/rust-litecoin#4]
Litecoin Space uses `rust-litecoin` + `electrs-ltc-esplora` as it backend, and incorrectly shows the wrong hogex address here: https://litecoinspace.org/tx/0be0f16834b12c652a548ceec145050e0cfa128f633c10bd255be3838f1980dd

Blockchair correctly encodes the hogex address here: https://blockchair.com/litecoin/transaction/0be0f16834b12c652a548ceec145050e0cfa128f633c10bd255be3838f1980dd

**Comment by webwarrior-ws** [comment]
This is strange.
Hex encoding of transaction in question that litecoinspace outputs is:
```
02000000014c6760f58df93356b4f23ab8be1f33b44be814bdfafb77c9758682d39d492eb50000000000ffffffff012c8a768b1c030000225820638c6c06eef97d9155e56990ad0cf3358ce00b47609f132750cbd05364db58da00000000
```
But Litecoin-core and e.g. https://api.blockcypher.com/v1/ltc/main/txs/0be0f16834b12c652a548ceec145050e0cfa128f633c10bd255be3838f1980dd?limit=50&includeHex=true give another hex encoding:
```
020000000008014c6760f58df93356b4f23ab8be1f33b44be814bdfafb77c9758682d39d492eb50000000000ffffffff012c8a768b1c030000225820638c6c06eef97d9155e56990ad0cf3358ce00b47609f132750cbd05364db58da0000000000
```
When I try to parse the latter with `rust-litecoin`, i get `ParseFailed("data not consumed entirely when explicitly deserializing")`:
https://github.com/webwarrior-ws/rust-litecoin/actions/runs/8436314492/job/23103537864

**Comment by webwarrior-ws** [comment]
Nevermind, I was using wrong branch. On `ltc` branch, transaction gets parsed successfully.

**Comment by knocte** [comment]
@losh11 please review: https://github.com/rust-litecoin/rust-litecoin/pull/5

**Comment by losh11** [comment]
Witness version 9 (which indicates a pegin address) also should be using
bech32, not bech32m. Otherwise seems valid for hogex.
